### ISSUE TITLE
tie_client.get_file_reputation does not return External Reputation

### ISSUE THREAD

**Issue by mohlcyber** [opendxl/opendxl-tie-client-python#15]
The TIE get_file_reputation does not return any external reputation values (providerId 15).
Only subscribing to TIE reputation-changes will provide the external reputation.
Guess this is more an issue on the TIE part.

**Comment by delavegamatias** [comment]
This seems to be a configuration issue, only TIE Server needs to listen to the external file reputation report, not the client implementation. With External Reputation Provider if TIE Server doesn't have a reputation from the provider yet (Not Available), no entry associated with the provider ID 15 will be included in the file reputation response (even if External Reputation Provider is enabled in the Policy). The same happens with ATD or MWG reputation providers.  
I think the External Reputation Provider might not have been enabled in TIE Server Management policy in this case, and therefore when a report is sent, TIE Server is not processing it, that’s why it’s not returning the External Reputation in the response, because it’s simply not in the database. Can you please double check your TIE Server policy and make sure that External Reputation Provider checkbox is checked in the policy? If it is, please verify the External Reputation is available in the TIE Reputations page to confirm it exists in the TIE Server database.

**Comment by mohlcyber** [comment]
Hi Delavegamatias, 
thanks for your response. Of course the external reputation provider is enables in TIE and a reputation has been set. Please find some screenshots below.

<img width="1229" alt="Screenshot 2019-12-12 at 11 53 24" src="https://user-images.githubusercontent.com/25227268/70681387-26567200-1cd6-11ea-8c71-1ef548745d55.png">

The DXL output to get the TIE file rep returns the following:

```
{
  "1": {
    "attributes": {
      "2120340": "0"
    },
    "createDate": 1541593102,
    "providerId": 1,
    "trustLevel": 0
  },
  "3": {
    "attributes": {
      "2098277": "18",
      "2101652": "4",
      "2102165": "1541593102",
      "2111893": "1731",
      "2112148": "15",
      "2112404": "50",
      "2112660": "33",
      "2114965": "1",
      "2123156": "0",
      "2138520": "CQBjAAAAAQCDBA==",
      "2139285": "216172782113784268"
    },
    "createDate": 1541593102,
    "providerId": 3,
    "trustLevel": 1
  },
  "5": {
    "attributes": {
      "4194962": "0",
      "4195218": "0",
      "4195474": "4",
      "4195730": "4",
      "4195988": "3",
      "4196244": "4",
      "4196500": "2",
      "4196756": "4",
      "4197012": "2",
      "4197268": "2",
      "4197524": "2",
      "4197784": "aQCDAIUAzwDRAN8A6gD4APoA+wD+AAABBgEJAREBlgGZAZsBqwH6ARoCIQIoAjcC0wI5A9YH8giECdsJ4QniCegJ",
      "4198552": "CQBjAAAAAQCDBA=="
    },
    "createDate": 1541593265,
    "providerId": 5,
    "trustLevel": 15
  }
}

```

I cannot find the external reputation information in the DXL response. Maybe i am missing something.

Thanks again for your support.

**Comment by mohlcyber** [comment]
Thanks for the call. Issue is resolved. I am now able to retrieve the external reputation as well. Issue can be closed.
